### ISSUE TITLE
--replaces-process throws exception in multiprocessing

### ISSUE THREAD

**Issue by GregPK** [phuhl/notify-send.py#24]
Script runs fine in all other cases, but running with `--replaces-process`  on my machine like so:

```bash
notify-send.py --replaces-process testrep "Test replaces"
```

causes:
```
Traceback (most recent call last):
  File "/home/gregpk/.local/pipx/venvs/notify-send-py/lib/python3.11/site-packages/notify_send_py/notify_send_py.py", line 126, in notify
    conn = Client(pidf.read())
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 513, in Client
    family = family or address_type(address)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 109, in address_type
    raise ValueError('address type of %r unrecognized' % address)
ValueError: address type of b'' unrecognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregpk/.local/bin/notify-send.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gregpk/.local/pipx/venvs/notify-send-py/lib/python3.11/site-packages/notify_send_py/notify_send_py.py", line 218, in main
    NotifySendPyCLI()
  File "/home/gregpk/.local/pipx/venvs/notify-send-py/lib/python3.11/site-packages/notify_send_py/notify_send_py.py", line 199, in __init__
    n_id = NotifySendPy().notify(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gregpk/.local/pipx/venvs/notify-send-py/lib/python3.11/site-packages/notify_send_py/notify_send_py.py", line 132, in notify
    pidf.write(listener.address)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by TimP4w** [comment]
I have the same issue (`Python 3.11.6`)

```
                   -`                    timp4w@arch 
                  .o+`                   ----------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 6.6.8-arch1-1 
               `+oooooo:                 Uptime: 3 hours, 22 mins 
               -+oooooo+:                Packages: 1018 (pacman), 12 (flatpak) 
             `/:-:++oooo+:               Shell: zsh 5.9 
            `/++++/+++++++:              Resolution: 2560x1440 
           `/++++++++++++++:             DE: Hyprland 
          `/+++ooooooooooooo/`           WM: sway 
         ./ooosssso++osssssso+`          Terminal: kitty 
        .oossssso-````/ossssss+`         CPU: Intel i7-9700K (8) @ 4.900GHz 
       -osssssso.      :ssssssso.        GPU: NVIDIA GeForce RTX 2070 Rev. A 
      :osssssss/        osssso+++.       Memory: 3620MiB / 32015MiB 
     /ossssssss/        +ssssooo/-
   `/ossssso+/:-        -:/+osssso+-                             
  `+sso+:-`                 `.-/+oso:                            
 `++:.                           `-/+/
 .`                                 `/


```

**Comment by tetsugakusha256** [comment]
Same issue here on arch too.
Python 3.11.6
Installed notify-send.py through AUR where notify-send-py has Version: 1.2.7-1

**Comment by phuhl** [comment]
Unfortunately I don't have time to work on a fix, currently. But PR is always welcome

**Comment by Qu4tro** [comment]
This is fixed on main actually. It just needs a new release.

**Comment by vincentaxhe** [comment]
notify-send is capable of replace id now, as long as in a loop.
use -p to emit id, -r to replace id. I give up using notify-send.py with my deadd-notification, only volume notification is not ideal。

**Comment by ArchWand** [comment]
> notify-send is capable of replace id now, as long as in a loop. use -p to emit id, -r to replace id. I give up using notify-send.py with my deadd-notification, only volume notification is not ideal。

Thank you so much, I was pulling my hair out over this
